push:
  categories:
    - name: door_unlocked_too_long_push
      identifier: door_unlocked_too_long_push
      actions:
        - identifier: 'LOCK_DOOR'
          title: 'Lock the Door'
          activationMode: 'background'
          authenticationRequired: yes
          destructive: no
