default_view:
  name: Home
  view: yes
  entities:
    - alarm_control_panel.abode_alarm
    - binary_sensor.ring_front_door_ding
    - sensor.ring_front_door_battery
    - climate.house
    - lock.front_door_lock
    - lock.back_door_lock
    - device_tracker.andrewsiphone
    - device_tracker.bentonsiphone
    - binary_sensor.east_door
    - binary_sensor.west_door
