great_room:
  name: Great Room
  view: yes
  entities:
    - fan.living_room_ceiling_fan
    - media_player.living_room
    - light.bookshelf_lamp
    - light.couch_light
    - light.dining_table_lights
    - light.fireplace_light
    - light.living_room_ceiling_lights
    - light.reading_chair_light
    - light.tv_lights
    - switch.kitchen_bar_lights
    - light.kitchen_ceiling_lights
    - light.kitchen_sink_lights
    - switch.over_cabinet_lights
    - switch.under_cabinet_lights
    - switch.wax_diffuser
    - switch.christmas_tree
