great_room:
  name: Great Room
  view: yes
  entities:
    - switch.wax_diffuser
    - switch.over_cabinet_lights
    - switch.under_cabinet_lights
    - light.bookshelf_light_level
    - light.couch_light_level
    - light.dining_table_lights_level_3
    - light.fireplace_light_level
    - light.living_room_ceiling_lights_level
    - light.reading_chair_light_level
    - light.tv_lights_level
    - switch.bar_lights_switch
    - light.kitchen_ceiling_lights_level
    - light.kitchen_sink_lights_level
    - fan.living_room_fan
    - media_player.living_room
    - switch.christmas_tree
