great_room_lights:
  name: Great Room Lights
  view: no
  entities:
    - light.bookshelf_light_level
    - light.couch_light_level
    - light.dining_table_lights_level_3
    - light.fireplace_light_level
    - light.living_room_ceiling_lights_level
    - light.reading_chair_light_level
    - light.tv_lights_level
    - switch.bar_lights_switch
    - light.kitchen_ceiling_lights_level
    - light.kitchen_sink_lights_level
    - switch.over_cabinet_lights
    - switch.under_cabinet_lights
    - switch.wax_diffuser
    - switch.christmas_tree
