master_suite:
  name: Master Suite
  view: yes
  entities:
    - light.master_bedroom_ceiling_lights_level
    - light.bedside_light_level
    - switch.bedroom_closet_switch
    - switch.bedroom_fan_light_switch
    - switch.rock_salt_lamp_switch
    - binary_sensor.master_bedroom_closet_door_sensor
    - fan.bedroom_fan
    - fan.bedside_fan
