east_door_lock_battery_level:
  friendly_name: Front Door Lock Battery Level
  value_template: "{{ states.zwave.east_door_lock.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
west_door_lock_battery_level:
  friendly_name: Back Door Lock Battery Level
  value_template: "{{ states.zwave.west_door_lock.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
utility_closet_door_battery_level:
  friendly_name: Utility Closet Door Sensor Battery Level
  value_template: "{{ states.zwave.aeotec_zw120_door_window_sensor_gen5.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
server_closet_door_battery_level:
  friendly_name: Server Closet Door Sensor Battery Level
  value_template: "{{ states.zwave.aeotec_zw120_door_window_sensor_gen5_2.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
coat_closet_door_battery_level:
  friendly_name: Coat Closet Door Sensor Battery Level
  value_template: "{{ states.zwave.coat_closet_door_sensor.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
bedroom_closet_motion_detector_battery_level:
  friendly_name: Bedroom Closet Motion Battery Level
  value_template: "{{ states.zwave.ecolink_motion_detector.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
laundry_door_battery_level:
  friendly_name: Laundry Door Sensor Battery Level
  value_template: "{{ states.zwave.laundry_door_sensor.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
bedroom_closet_door_door_battery_level:
  friendly_name: Bedroom Closet Door Sensor Battery Level
  value_template: "{{ states.zwave.master_bedroom_closet_door.attributes.battery_level }}"
  unit_of_measurement: "%"
  device_class: battery
east_door_battery_low:
  friendly_name: East Door Sensor Motion Battery Low
  value_template: "{{ states.binary_sensor.east_door.attributes.battery_low }}"
west_door_battery_low:
  friendly_name: West Door Sensor Motion Battery Low
  value_template: "{{ states.binary_sensor.west_door.attributes.battery_low }}"
patio_door_battery_low:
  friendly_name: Patio Door Sensor Motion Battery Low
  value_template: "{{ states.binary_sensor.patio_door.attributes.battery_low }}"
hallway_motion_battery_low:
  friendly_name: Hallway Motion Battery Low
  value_template: "{{ states.binary_sensor.hallway.attributes.battery_low }}"
great_room_motion_battery_low:
  friendly_name: Great Room Motion Battery Low
  value_template: "{{ states.binary_sensor.hallway.attributes.battery_low }}"
keyfob_one_battery_low:
  friendly_name: Keyfob One Battery Low
  value_template: "{{ states.binary_sensor.keyfob.attributes.battery_low }}"
keyfob_two_battery_low:
  friendly_name: Keyfob Two Battery Low
  value_template: "{{ states.binary_sensor.keyfob_2.attributes.battery_low }}"
keypad_battery_low:
  friendly_name: Keypad Battery Low
  value_template: "{{ states.binary_sensor.keypad.attributes.battery_low }}"
east_door_battery_low:
  friendly_name: East Door Sensor Motion Battery Low
  value_template: "{{ states.binary_sensor.east_door.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.east_door.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
west_door_battery_low:
  friendly_name: West Door Sensor Motion Battery Low
  value_template: "{{ states.binary_sensor.west_door.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.west_door.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
patio_door_battery_low:
  friendly_name: Patio Door Sensor Motion Battery Low
  value_template: "{{ states.binary_sensor.patio_door.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.patio_door.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
hallway_motion_battery_low:
  friendly_name: Hallway Motion Battery Low
  value_template: "{{ states.binary_sensor.hallway.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.hallway.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
great_room_motion_battery_low:
  friendly_name: Great Room Motion Battery Low
  value_template: "{{ states.binary_sensor.great_room.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.great_room.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
keyfob_one_battery_low:
  friendly_name: Keyfob One Battery Low
  value_template: "{{ states.binary_sensor.keyfob.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.keyfob.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
keyfob_two_battery_low:
  friendly_name: Keyfob Two Battery Low
  value_template: "{{ states.binary_sensor.keyfob_2.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.keyfob_2.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
keypad_battery_low:
  friendly_name: Keypad Battery Low
  value_template: "{{ states.binary_sensor.keypad.attributes.battery_low }}"
  icon_template: >-
    {% if states.binary_sensor.keypad.attributes.battery_low == true %}
      mdi:battery-20
    {% else %}
      mdi:battery
    {% endif %}
