- platform: template
  fans:
    bedroom_fan:
      friendly_name: "Bedroom fan"
      value_template: "{{states('switch.bedroom_fan_switch')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.bedroom_fan_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.bedroom_fan_switch
      speeds: []
    living_room_fan:
      friendly_name: "Living room fan"
      value_template: "{{states('switch.living_room_fan_switch')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_fan_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.living_room_fan_switch
      speeds: []
    bedside_fan:
      friendly_name: "Bedside fan"
      value_template: "{{states('switch.bedside_fan_switch')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.bedside_fan_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.bedside_fan_switch
      speeds: []
