#!/bin/bash

if [[ ! -z "$DEBUG" ]]; then debug='--debug'; fi
sudo /opt/puppetlabs/bin/puppet \
  apply \
  $1 \
  $debug \
  --modulepath=modules:vendor \
  --hiera_config=hiera.yaml \
  --show_diff \
  nodes/site.pp
