#!/bin/bash

if [[ "$(lsb_release -sc)" = "stretch" ]]; then
  prefix="/opt/puppetlabs/bin/"
fi

if [[ ! -z "$DEBUG" ]]; then debug='--debug'; fi
sudo ${prefix}puppet \
  apply \
  $1 \
  $debug \
  --modulepath=modules:vendor \
  --hiera_config=hiera.yaml \
  --show_diff \
  nodes/site.pp
