#!/bin/bash

dir=$(pwd)
distro='stretch'
puppet_major_version='5'
agent_version=''

release_pkg="puppet$puppet_major_version-release"
agent_pkg="puppet-agent$agent_version"
puppet_bin='/opt/puppetlabs/bin/puppet'

function section() {
  echo
  echo -n "===================="
  echo -n "===================="
  echo    "===================="
  echo "$1..."
  echo -n "===================="
  echo -n "===================="
  echo -n "===================="
  echo
}

function installed() {
  sudo dpkg -s $1 2>/dev/null | grep -q 'Status: install ok installed'
}

function apt() {
  section "installing $1"
  if ! installed $1; then
    sudo apt-get install -qq $1
  fi
}

function puppetmodule() {
  if ! $puppet_bin module list --modulepath vendor 2>/dev/null | grep -q $1; then
    section "installing puppet module $1"
    $puppet_bin module install --target-dir vendor --modulepath vendor $1
  fi
}

section "bootstrapping puppet for debian $distro"
section "installing dependencies"
apt "jq hiera-eyaml"

section "installing $release_pkg apt repo"
if ! installed $release_pkg ; then
  cd /tmp
  wget "http://apt.puppetlabs.com/$release_pkg-$distro.deb"
  sudo dpkg -i ./$release_pkg-$distro.deb
  rm ./$release_pkg-$distro.deb
  sudo apt-get update 2>/dev/null
  cd $dir
fi

section "installing puppet"
apt "$agent_pkg"
sudo systemctl stop puppet || /bin/true
sudo systemctl disable puppet || /bin/true
sudo systemctl disable mcollective || /bin/true

puppetmodule "puppetlabs-docker"
puppetmodule "puppet-archive"

section "done!"
