#!/bin/bash

dir=$(pwd)
distro=$(lsb_release -cs)
puppet_major_version='5'
agent_version=''

release_pkg="puppet$puppet_major_version-release"
agent_pkg="puppet-agent$agent_version"
puppet_bin='/opt/puppetlabs/bin/puppet'

dependencies='jq hiera-eyaml librarian-puppet'

function section() {
  echo
  echo -n "===================="
  echo -n "===================="
  echo    "===================="
  echo "$1..."
  echo -n "===================="
  echo -n "===================="
  echo -n "===================="
  echo
}

function installed() {
  [[ `dpkg -s "$@" 2>&1 | grep -c 'is not installed'` == '0' ]]
}

function apt() {
  if ! installed "$@"; then
    sudo apt-get install -qq "$@"
  fi
}

section "bootstrapping puppet for debian $distro"
section "installing dependencies: $dependencies"
apt $dependencies

if [[ "$distro" == "stretch" ]]; then
  section "installing $release_pkg apt repo"
  if ! installed $release_pkg ; then
    cd /tmp
    wget "http://apt.puppetlabs.com/$release_pkg-$distro.deb"
    sudo dpkg -i ./$release_pkg-$distro.deb
    rm ./$release_pkg-$distro.deb
    sudo apt-get update 2>/dev/null
    cd $dir
  fi

  section "installing puppet"
  apt "$agent_pkg"
  sudo systemctl stop puppet || /bin/true
  sudo systemctl disable puppet || /bin/true
  sudo systemctl disable mcollective || /bin/true
else
  installed "puppet" || apt "puppet"
fi

section "installing puppet module dependencies"
librarian-puppet install --path vendor

section "done!"
