- id: start_homekit
  alias: Start HomeKit
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
  action:
    - service: homekit.start

- id: zwave_heal
  alias: 'heal at 3:30am'
  trigger:
    platform: time
    at: '03:30:00'
  action:
    service: zwave.heal_network

- id: utility_closet_lights
  alias: Utility closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.utility_closet_door_sensor
  action:
    entity_id: light.utility_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: server_closet_lights
  alias: Server closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.server_closet_door_sensor
  action:
    entity_id: light.server_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: laundry_closet_lights
  alias: Laundry closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_closet_door_sensor
  action:
    entity_id: light.laundry_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: coat_closet_lights
  alias: Coat closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.coat_closet_door_sensor
  action:
    entity_id: light.coat_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: office_closet_lights
  alias: Office closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.office_closet_door_sensor
  action:
    entity_id: light.office_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: guest_bedroom_closet_lights
  alias: Guest bedroom closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.guest_bedroom_closet_door_sensor
  action:
    entity_id: light.guest_bedroom_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: master_bedroom_closet_lights
  alias: Master bedroom closet lights
  trigger:
    platform: state
    entity_id: binary_sensor.master_bedroom_closet_door_sensor
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.master_bedroom_closet_door_sensor
        state: 'on'
      - condition: state
        entity_id: binary_sensor.master_bedroom_closet_motion_detector
        state: 'off'
  action:
    entity_id: light.master_bedroom_closet_lights
    service_template: "light.turn_{{ trigger.to_state.state }}"

- id: master_bedroom_closet_lights_auto
  alias: Master bedroom closet lights auto
  trigger:
    platform: state
    entity_id: binary_sensor.master_bedroom_closet_motion_detector
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.master_bedroom_closet_lights

- id: front_door_unlocked_too_long_automation
  alias: Door unlocked notification
  trigger:
    platform: state
    entity_id: lock.front_door_lock
    to: unlocked
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: binary_sensor.east_door
      state: 'off'
  action:
    service: notify.ios_andrews_iphone
    data:
      message: "The front door has been unlocked for 10 minutes."
      data:
        push:
          badge: 1
          sound: default
          category: front_door_unlocked_too_long_push
        action_data:
          entity_id: lock.front_door_lock

- id: lock_front_door_from_ios
  alias: Lock the door from iOS notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: 'LOCK_DOOR'
  action:
    service: lock.lock
    entity_id: lock.front_door_lock

- id: back_door_unlocked_too_long_automation
  alias: Door unlocked notification
  trigger:
    platform: state
    entity_id: lock.back_door_lock
    to: unlocked
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: binary_sensor.west_door
      state: 'off'
  action:
    service: notify.ios_andrews_iphone
    data:
      message: "The back door has been unlocked for 10 minutes."
      data:
        push:
          badge: 1
          sound: default
          category: back_door_unlocked_too_long_push
        action_data:
          entity_id: lock.back_door_lock

- id: lock_back_door_from_ios
  alias: Lock the door from iOS notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: 'LOCK_DOOR'
  action:
    service: lock.lock
    entity_id: lock.back_door_lock
