homeassistant:
  name: Home
  latitude: 41.9403
  longitude: -87.6486
  elevation: 180.4
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
frontend:
config:
http:
  base_url: !secret base_url
updater:
  include_used_components: true
history:
logbook:
map:
sun:
google_assistant:
  api_key: !secret google_assistant_api_key
  project_id: !secret google_assistant_project_id
  expose_by_default: true
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
recorder:
  db_url: !secret postgres_url
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  autoheal: false
  device_config_domain:
    light:
      refresh_value: True
      delay: 5
abode:
  username: !secret abode_username
  password: !secret abode_password
device_tracker:
  - platform: unifi
    consider_home: 300
    #track_new_devices: no
    host: 192.168.0.210
    port: 8443
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
    ssid_filter:
      - 'skynet'
ios: !include ios.yaml
ring:
  username: !secret ring_username
  password: !secret ring_password
sensor:
  - platform: ring
  - platform: template
    sensors: !include device_types/battery.yaml
  - platform: awair
    access_token: !secret awair_access_token
binary_sensor:
  - platform: ring
panel_custom:
  name: zwavegraph2
  sidebar_title: ZWave Graph2
  sidebar_icon: mdi:access-point-network
  url_path: zwave
wake_on_lan:
fan: !include device_types/fan.yaml
media_player: !include device_types/media_player.yaml
group: !include_dir_merge_named group/
automation: !include automations.yaml
scene: !include scene.yaml
homekit: !include homekit.yaml
cloud: !include cloud.yaml
apple_tv: !include device_types/apple_tv.yaml
script: !include_dir_named script/
input_select: !include input/input_select.yaml
python_script:
logger:
  default: info
  logs:
    custom_components.lock.zwave: debug
