homeassistant:
  name: Home
  latitude: 41.9403
  longitude: -87.6486
  elevation: 180.4
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
config:
frontend:
history:
logbook:
map:
sun:
wake_on_lan:
http:
  base_url: !secret base_url
updater:
  include_used_components: true
recorder:
  db_url: !secret postgres_url
system_health:
zwave: !include zwave.yaml
logger:
  default: info
  logs:
    custom_components.lock.zwave: debug
    custom_components.sensor.kryptonite: debug
    homeassistant.components.cloud.iot: debug
    homeassistant.components.cloud: debug
    homeassistant.components.google_assistant: debug

abode: !include platforms/abode.yaml
nest: !include platforms/nest.yaml
ring: !include platforms/ring.yaml

apple_tv: !include device_types/apple_tv.yaml
binary_sensor: !include device_types/binary_sensor.yaml
fan: !include device_types/fan.yaml
googlehome: !include device_types/googlehome.yaml
light: !include device_types/light.yaml
media_player: !include device_types/media_player.yaml
remote: !include device_types/remote.yaml
sensor: !include device_types/sensor.yaml
switch: !include device_types/switch.yaml

group: !include_dir_merge_named group/
input_select: !include input/input_select.yaml
script: !include_dir_named script/

automation: !include automations.yaml
cloud: !include cloud.yaml
device_tracker: !include device_tracker.yaml
homekit: !include homekit.yaml
ios: !include ios.yaml
panel_custom: !include panel_custom.yaml
scene: !include scene.yaml
