binary_sensor.laundry_closet_door_sensor:
  device_class: door
  icon: mdi:door
binary_sensor.master_bedroom_closet_door_sensor:
  device_class: door
  icon: mdi:door
binary_sensor.coat_closet_door_sensor:
  device_class: door
  icon: mdi:door
binary_sensor.utility_closet_door_sensor:
  device_class: door
  icon: mdi:door
binary_sensor.master_bedroom_closet_motion_detector:
  device_class: occupancy
  icon: mdi:door
binary_sensor.server_closet_door_sensor:
  device_class: door
  icon: mdi:door
binary_sensor.east_door:
  device_class: door
  icon: mdi:door
binary_sensor.west_door:
  device_class: door
  icon: mdi:door
binary_sensor.patio_door:
  device_class: door
  icon: mdi:door
switch.christmas_tree:
  icon: mdi:pine-tree
switch.hallway_christmas_lights:
  icon: mdi:pine-tree
