auto_start: False
filter:
  include_domains:
    - light
    - lock
    - alarm_control_panel
    - fan
    - climate
  include_entities:
    - binary_sensor.east_door
    - binary_sensor.west_door
    - binary_sensor.patio_door
    - sensor.house_thermostat_humidity
    - switch.apple_tv
    - switch.playstation_4
    - switch.tv
    - switch.xbox_one
    - switch.wax_diffuser
