- name: Bedtime
  entities:
    switch.master_bedroom_closet_lights: off
    switch.master_bedroom_rock_salt_lamp: off
    light.master_bedroom_ceiling_lights: off
    light.master_bedroom_bedside_lamp: off
    switch.master_bedroom_fan_lights: off
    fan.master_bedroom_ceiling_fan: on
    fan.master_bedroom_bedside_fan: on
    lock.front_door_lock: locked
    lock.back_door_lock: locked
    alarm_control_panel.abode_alarm: armed_home
- name: Morning
  entities:
    switch.master_bedroom_fan_lights: on
    fan.master_bedroom_ceiling_fan: off
    fan.master_bedroom_bedside_fan: off
    alarm_control_panel.abode_alarm: disarmed
- name: Work
  entities:
    light.downstairs_hallway_lights: on
    light.stairway_lights: on
    light.office_ceiling_lights: on
- name: xbox_one
  entities:
    script.turn_on_xbox_one: on
    media_player.playstation_4: off
    media_player.living_room_apple_tv: off
    # media_player.vr: off
- name: playstation_4
  entities:
    media_player.xbox_one: off
    media_player.playstation_4: on
    media_player.living_room_apple_tv: off
    # media_player.vr: off
- name: living_room_apple_tv
  entities:
    media_player.xbox_one: off
    media_player.playstation_4: off
    media_player.living_room_apple_tv: on
    # media_player.vr: off
#- name: vr
    #entities:
    #media_player.xbox_one: off
    #media_player.playstation_4: off
    #media_player.living_room_apple_tv: off
    # media_player.vr: on
