usb_path: /dev/ttyACM0
network_key: !secret zwave_network_key
autoheal: false
device_config_domain:
  light:
    refresh_value: True
    delay: 5
device_config:
  light.master_bedroom_bedside_lamp:
    refresh_value: False
