alias: Turn on the ps4 (google action)
sequence:
  - service: media_player.turn_on
    data:
      entity_id: media_player.living_room
  - service: media_player.select_source
    data:
      entity_id: media_player.living_room
      source: media_player.playstation_4
