alias: Turn on the apple tv (google action)
sequence:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.living_room_universal
      option: media_player.living_room_apple_tv
  - service: media_player.turn_on
    data:
      entity_id: media_player.living_room
