alias: Turn on Living Room Universal Media Player
sequence:
  - service: media_player.turn_on
    data:
      entity_id: media_player.receiver
  - service: media_player.turn_on
    data:
      entity_id: media_player.living_room_tv
  - wait_template: "{{ states('media_player.living_room_tv') != 'off' }}"
    timeout: '00:00:02'
    continue_on_timeout: 'true'
  - service: media_player.turn_on
    data:
      entity_id: media_player.living_room_tv
  - wait_template: "{{ states('media_player.living_room_tv') != 'off' }}"
    timeout: '00:00:02'
    continue_on_timeout: 'true'
  - service: media_player.turn_on
    data:
      entity_id: media_player.living_room_tv
  - service: script.select_source_living_room_universal
    data_template:
      source: "{{ states('input_select.living_room_universal') }}"
