great_room_lights:
  name: Great Room Lights
  view: no
  entities:
    - light.bookshelf_lamp
    - light.couch_light
    - light.dining_table_lights
    - light.fireplace_light
    - light.living_room_ceiling_lights
    - light.reading_chair_light
    - light.tv_lights
    - light.kitchen_bar_lights
    - light.kitchen_ceiling_lights
    - light.kitchen_sink_lights
    - light.kitchen_over_cabinet_lights
    - light.kitchen_under_cabinet_lights
    - switch.wax_diffuser
