hallway:
  name: Hallway
  view: yes
  entities:
    - alarm_control_panel.abode_alarm
    - lock.front_door_lock
    - lock.back_door_lock
    - light.upstairs_hallway_lights
    - light.stairway_lights
    - binary_sensor.ring_front_door_ding
    - binary_sensor.east_door
    - binary_sensor.west_door
