living_room:
  name: Living Room
  view: yes
  entities:
    - light.bookshelf_lamp
    - light.couch_light
    - light.dining_table_lights
    - light.fireplace_light
    - light.living_room_ceiling_lights
    - light.reading_chair_light
    - light.tv_lights
    - fan.living_room_ceiling_fan
    - media_player.living_room
    - light.christmas_tree
