utility:
  name: Utility
  view: yes
  entities:
    - binary_sensor.coat_closet_door_sensor
    - binary_sensor.laundry_closet_door_sensor
    - light.coat_closet_lights
    - light.laundry_closet_lights
    - light.utility_closet_lights
    - light.server_closet_lights
