- name: Living Room
  host: 192.168.10.5
  login_id: !secret apple_tv_living_room_login_id
  start_off: true
- name: Bedroom
  host: 192.168.10.6
  login_id: !secret apple_tv_bedroom_login_id
  start_off: true
