- platform: template
  fans:
    master_bedroom_ceiling_fan:
      friendly_name: "Master Bedroom Ceiling Fan"
      value_template: "{{states('switch.master_bedroom_ceiling_fan')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.master_bedroom_ceiling_fan
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.master_bedroom_ceiling_fan
      speeds: []
    living_room_ceiling_fan:
      friendly_name: "Living Room Ceiling Fan"
      value_template: "{{states('switch.living_room_ceiling_fan')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.living_room_ceiling_fan
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.living_room_ceiling_fan
      speeds: []
    master_bedroom_bedside_fan:
      friendly_name: "Master Bedroom Bedside Fan"
      value_template: "{{states('switch.master_bedroom_bedside_fan')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.master_bedroom_bedside_fan
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.master_bedroom_bedside_fan
      speeds: []
