devices:
  - host: 192.168.0.62 # living_room
    track_devices: false
    track_alarms: true
  - host: 192.168.0.66 # kitchen
    track_devices: false
    track_alarms: true
  - host: 192.168.0.63 # master bedroom
    track_devices: false
    track_alarms: true
  - host: 192.168..65 # guest bedroom
    track_devices: false
    track_alarms: true
  - host: 192.168.0.64 # office
    track_devices: false
    track_alarms: true
