devices:
  - host: 192.168.20.3 # living_room
    track_devices: false
    track_alarms: true
  - host: 192.168.20.7 # kitchen
    track_devices: false
    track_alarms: true
  - host: 192.168.20.10 # master bedroom
    track_devices: false
    track_alarms: true
  - host: 192.168.20.8 # guest bedroom
    track_devices: false
    track_alarms: true
  - host: 192.168.20.4 # office
    track_devices: false
    track_alarms: true
