devices:
  - host: 192.168.0.3   # living_room
    track_devices: false
    track_alarms: true
  - host: 192.168.0.237 # kitchen
    track_devices: false
    track_alarms: true
  - host: 192.168.0.147 # master bedroom
    track_devices: false
    track_alarms: true
  - host: 192.168.0.221 # guest bedroom
    track_devices: false
    track_alarms: true
  - host: 192.168.0.220 # office
    track_devices: false
    track_alarms: true
