- platform: ring
- platform: template
  sensors: !include battery.yaml
- platform: awair
  access_token: !secret awair_access_token
- platform: kryptonite
  username: !secret nest_username
  password: !secret nest_password
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
